import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { createStateIndex, popcount15 } from '../solver/state-index.mjs';
import { createDiceUniverse } from '../solver/dice.mjs';
import { PolicyEngine } from '../solver/query.mjs';
import { readTables } from '../solver/table-format.mjs';
import { CATEGORY_NAMES } from '../solver/scoring.mjs';
import { SIM_HEADER_SIZE, SIM_RECORD_SIZE } from '../solver/simulation.mjs';
import { ensureDir, writeJsonAtomic } from '../util/fs.mjs';
import { csvRow } from '../util/csv.mjs';
import { normal95, normal99, quantileFromHistogram, wilsonInterval, pearsonFromSums } from '../util/statistics.mjs';
import { barChart, lineChart, heatmap, architectureSvg } from './charts.mjs';

function mergeAggregate(a,b){if(!a)return structuredClone(b);for(const k of ['n','sum','sumSq','bonusCount','yatzyGameCount','earlyScoreDecisions','rerollDecisions','tieDecisions','actionScoreCount','actionRerollCount'])a[k]+=b[k];a.min=Math.min(a.min,b.min);a.max=Math.max(a.max,b.max);for(const k of ['histogram','upperHistogram','categorySum','categorySumSq','categoryZero','categoryFillTurnSum','turnCumulativeSum','turnUpperSum','turnBonusCount','keeperCounts','marginHistogram'])for(let i=0;i<a[k].length;i++)a[k][i]+=b[k][i];for(let c=0;c<15;c++)for(let t=0;t<16;t++)a.categoryFillTurnHist[c][t]+=b.categoryFillTurnHist[c][t];return a;}
function statsFromAgg(a){const mean=a.sum/a.n;const variance=(a.sumSq-a.sum*a.sum/a.n)/(a.n-1);const sd=Math.sqrt(Math.max(0,variance)),se=sd/Math.sqrt(a.n);return{n:a.n,mean,sd,se,ci95:normal95(mean,se),ci99:normal99(mean,se),min:a.min,max:a.max,median:quantileFromHistogram(a.histogram,.5),q01:quantileFromHistogram(a.histogram,.01),q05:quantileFromHistogram(a.histogram,.05),q10:quantileFromHistogram(a.histogram,.1),q25:quantileFromHistogram(a.histogram,.25),q75:quantileFromHistogram(a.histogram,.75),q90:quantileFromHistogram(a.histogram,.9),q95:quantileFromHistogram(a.histogram,.95),q99:quantileFromHistogram(a.histogram,.99)};}
function thresholdRows(hist,n){return[150,175,200,225,250,275,300,325,350].map(threshold=>({threshold,count:hist.slice(threshold).reduce((a,b)=>a+b,0),probability:hist.slice(threshold).reduce((a,b)=>a+b,0)/n}));}
function writeCsv(file,headers,rows){ensureDir(path.dirname(file));const fd=fs.openSync(file,'w');fs.writeSync(fd,csvRow(headers));for(const row of rows)fs.writeSync(fd,csvRow(headers.map(h=>row[h])));fs.closeSync(fd);}
function markdownTable(headers,rows){const line=x=>`| ${x.join(' | ')} |\n`;return line(headers)+line(headers.map(()=> '---'))+rows.map(r=>line(headers.map(h=>r[h]))).join('');}
function latexTable(headers,rows){return `\\begin{tabular}{${'l'.repeat(headers.length)}}\n\\hline\n${headers.join(' & ')} \\\\ \\hline\n${rows.map(r=>headers.map(h=>String(r[h]).replaceAll('%','\\%')).join(' & ')+' \\\\').join('\n')}\n\\hline\n\\end{tabular}\n`;}
async function writeLargeCsv(file,header,iterator){
  ensureDir(path.dirname(file));const fd=fs.openSync(file,'w');let buffer=csvRow(header);
  try{for await(const row of iterator){buffer+=csvRow(row);if(buffer.length>=1024*1024){fs.writeSync(fd,buffer);buffer='';}}if(buffer)fs.writeSync(fd,buffer);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}
}

function parseOptimalRecords(files,callback){const recordBuf=Buffer.alloc(SIM_RECORD_SIZE*20000);for(const file of files){const fd=fs.openSync(file,'r');const stat=fs.fstatSync(fd);const n=(stat.size-SIM_HEADER_SIZE)/SIM_RECORD_SIZE;let game=0;while(game<n){const count=Math.min(20000,n-game),bytes=count*SIM_RECORD_SIZE;fs.readSync(fd,recordBuf,0,bytes,SIM_HEADER_SIZE+game*SIM_RECORD_SIZE);for(let i=0;i<count;i++)callback(recordBuf,i*SIM_RECORD_SIZE,file,game+i);game+=count;}fs.closeSync(fd);}}
function pairedDifference(fileA,fileB){const fdA=fs.openSync(fileA,'r'),fdB=fs.openSync(fileB,'r');const n=Math.min((fs.fstatSync(fdA).size-SIM_HEADER_SIZE)/SIM_RECORD_SIZE,(fs.fstatSync(fdB).size-SIM_HEADER_SIZE)/SIM_RECORD_SIZE);const a=Buffer.alloc(SIM_RECORD_SIZE*20000),b=Buffer.alloc(SIM_RECORD_SIZE*20000);let sum=0,sumSq=0,min=Infinity,max=-Infinity,pos=0,zero=0;for(let start=0;start<n;start+=20000){const count=Math.min(20000,n-start),bytes=count*SIM_RECORD_SIZE;fs.readSync(fdA,a,0,bytes,SIM_HEADER_SIZE+start*SIM_RECORD_SIZE);fs.readSync(fdB,b,0,bytes,SIM_HEADER_SIZE+start*SIM_RECORD_SIZE);for(let i=0;i<count;i++){const d=a.readUInt16LE(i*SIM_RECORD_SIZE)-b.readUInt16LE(i*SIM_RECORD_SIZE);sum+=d;sumSq+=d*d;min=Math.min(min,d);max=Math.max(max,d);if(d>0)pos++;else if(d===0)zero++;}}fs.closeSync(fdA);fs.closeSync(fdB);const mean=sum/n,variance=(sumSq-sum*sum/n)/(n-1),sd=Math.sqrt(Math.max(0,variance)),se=sd/Math.sqrt(n);return{n,mean,sd,se,ci95:normal95(mean,se),min,max,optimalHigherFraction:pos/n,equalFraction:zero/n};}

export async function runAnalysis({runDir,manifest,valuesPath,boundsPath,simulationSummaries,verification,onProgress=()=>{}}){
  const analysisDir=ensureDir(path.join(runDir,'analysis')),tablesDir=ensureDir(path.join(runDir,'tables')),csvDir=ensureDir(path.join(tablesDir,'csv')),mdDir=ensureDir(path.join(tablesDir,'markdown')),texDir=ensureDir(path.join(tablesDir,'latex')),figSvg=ensureDir(path.join(runDir,'figures','svg')),figPng=ensureDir(path.join(runDir,'figures','png'));
  const optimal=simulationSummaries.filter(x=>x.policyId==='optimal'),comparisons=simulationSummaries.filter(x=>x.policyId!=='optimal');let pooled=null;for(const x of optimal)pooled=mergeAggregate(pooled,x.aggregate);const pooledStats=statsFromAgg(pooled);
  const runRows=optimal.map(x=>{const s=statsFromAgg(x.aggregate);return{run:x.id,seed:x.seed,games:s.n,mean:s.mean,sd:s.sd,se:s.se,ci95_low:s.ci95[0],ci95_high:s.ci95[1],bonus_frequency:x.aggregate.bonusCount/s.n,yatzy_frequency:x.aggregate.yatzyGameCount/s.n,min:s.min,max:s.max};});
  writeCsv(path.join(csvDir,'optimal_runs.csv'),Object.keys(runRows[0]),runRows);
  const thresholds=thresholdRows(pooled.histogram,pooled.n);writeCsv(path.join(csvDir,'score_threshold_probabilities.csv'),['threshold','count','probability'],thresholds);
  const distribution=pooled.histogram.map((count,score)=>({score,count,probability:count/pooled.n,cumulative:0,tail:0}));let cum=0,tail=pooled.n;for(const r of distribution){cum+=r.count;r.cumulative=cum/pooled.n;r.tail=tail/pooled.n;tail-=r.count;}writeCsv(path.join(csvDir,'score_distribution.csv'),['score','count','probability','cumulative','tail'],distribution);
  const categoryRows=CATEGORY_NAMES.map((name,c)=>{const mean=pooled.categorySum[c]/pooled.n,variance=(pooled.categorySumSq[c]-pooled.categorySum[c]**2/pooled.n)/(pooled.n-1);return{category:name,mean,sd:Math.sqrt(Math.max(0,variance)),zero_count:pooled.categoryZero[c],zero_frequency:pooled.categoryZero[c]/pooled.n,mean_fill_turn:pooled.categoryFillTurnSum[c]/pooled.n};});writeCsv(path.join(csvDir,'category_summary.csv'),Object.keys(categoryRows[0]),categoryRows);
  const fillRows=[];for(let c=0;c<15;c++)for(let t=1;t<=15;t++)fillRows.push({category:CATEGORY_NAMES[c],turn:t,count:pooled.categoryFillTurnHist[c][t],probability:pooled.categoryFillTurnHist[c][t]/pooled.n});writeCsv(path.join(csvDir,'category_fill_turns.csv'),Object.keys(fillRows[0]),fillRows);
  const turnRows=Array.from({length:15},(_,i)=>({turn:i+1,mean_cumulative_score:pooled.turnCumulativeSum[i]/pooled.n,mean_upper_subtotal:pooled.turnUpperSum[i]/pooled.n,bonus_probability:pooled.turnBonusCount[i]/pooled.n}));writeCsv(path.join(csvDir,'turn_trajectory.csv'),Object.keys(turnRows[0]),turnRows);
  const keeperRows=pooled.keeperCounts.map((count,size)=>({keeper_size:size,count,frequency:count/pooled.keeperCounts.reduce((a,b)=>a+b,0)}));writeCsv(path.join(csvDir,'keeper_sizes.csv'),Object.keys(keeperRows[0]),keeperRows);
  const marginEdges=[0,1e-12,1e-8,1e-6,1e-4,1e-3,1e-2,.05,.1,.5,1,2,5,10,Infinity];const marginRows=pooled.marginHistogram.map((count,i)=>({lower:marginEdges[i],upper:marginEdges[i+1],count,frequency:count/pooled.marginHistogram.reduce((a,b)=>a+b,0)}));writeCsv(path.join(csvDir,'decision_margins.csv'),Object.keys(marginRows[0]),marginRows);
  onProgress({progress:.15,detail:'Core simulation tables'});

  const conditional={bonus:{n:0,sum:0,hist:Array(375).fill(0)},noBonus:{n:0,sum:0,hist:Array(375).fill(0)},yatzy:{n:0,sum:0,hist:Array(375).fill(0)},noYatzy:{n:0,sum:0,hist:Array(375).fill(0)}};
  const corr=Array.from({length:15},()=>({sx:0,sy:0,sxx:0,syy:0,sxy:0,n:0}));const extremesHigh=[],extremesLow=[];
  parseOptimalRecords(optimal.map(x=>x.outputPath),(b,o,file,gameIndex)=>{const score=b.readUInt16LE(o),bonus=b.readUInt8(o+3)===1,yatzy=b.readUInt8(o+4)>0;for(const [flag,key] of [[bonus,bonus?'bonus':'noBonus'],[yatzy,yatzy?'yatzy':'noYatzy']]){void flag;const q=conditional[key];q.n++;q.sum+=score;q.hist[score]++;}for(let c=0;c<15;c++){const x=b.readUInt8(o+18+c),q=corr[c];q.n++;q.sx+=x;q.sy+=score;q.sxx+=x*x;q.syy+=score*score;q.sxy+=x*score;}const item={score,file:path.basename(file),gameIndex};extremesHigh.push(item);extremesHigh.sort((a,b)=>b.score-a.score);if(extremesHigh.length>1000)extremesHigh.length=1000;extremesLow.push(item);extremesLow.sort((a,b)=>a.score-b.score);if(extremesLow.length>1000)extremesLow.length=1000;});
  const condRows=Object.entries(conditional).map(([group,x])=>({group,n:x.n,mean:x.sum/x.n,median:quantileFromHistogram(x.hist,.5),q05:quantileFromHistogram(x.hist,.05),q95:quantileFromHistogram(x.hist,.95)}));writeCsv(path.join(csvDir,'conditional_score_statistics.csv'),Object.keys(condRows[0]),condRows);const corrRows=CATEGORY_NAMES.map((category,c)=>({category,correlation_with_final_score:pearsonFromSums(corr[c].n,corr[c].sx,corr[c].sy,corr[c].sxx,corr[c].syy,corr[c].sxy)}));writeCsv(path.join(csvDir,'category_correlations.csv'),Object.keys(corrRows[0]),corrRows);writeCsv(path.join(csvDir,'extreme_high_games.csv'),['score','file','gameIndex'],extremesHigh);writeCsv(path.join(csvDir,'extreme_low_games.csv'),['score','file','gameIndex'],extremesLow);
  onProgress({progress:.30,detail:'Conditional and correlation analysis'});

  const policyRows=[...optimal.slice(0,1),...comparisons].map(x=>{const s=statsFromAgg(x.aggregate);return{policy:x.policyId,label:x.policyId==='optimal'?'Optimal full-game policy':x.policyId,games:s.n,mean:s.mean,sd:s.sd,loss_vs_optimal:pooledStats.mean-s.mean,bonus_frequency:x.aggregate.bonusCount/s.n,yatzy_frequency:x.aggregate.yatzyGameCount/s.n,min:s.min,max:s.max};});const optimalFile=optimal[0].outputPath;for(const row of policyRows){if(row.policy==='optimal'){row.paired_mean_loss=0;row.paired_ci95_low=0;row.paired_ci95_high=0;}else{const sim=comparisons.find(x=>x.policyId===row.policy),paired=pairedDifference(optimalFile,sim.outputPath);row.paired_mean_loss=paired.mean;row.paired_ci95_low=paired.ci95[0];row.paired_ci95_high=paired.ci95[1];row.optimal_higher_fraction=paired.optimalHigherFraction;}}writeCsv(path.join(csvDir,'policy_comparison.csv'),Object.keys(policyRows[0]),policyRows);
  onProgress({progress:.42,detail:'Policy comparisons'});

  const stateIndex=createStateIndex(),stateTables=readTables(valuesPath,boundsPath,stateIndex.totalStates);
  await writeLargeCsv(path.join(analysisDir,'turn_boundary_states.csv'),['state_index','used_mask','upper_total','used_category_count','unused_category_count','value_midpoint','value_lower','value_upper','interval_width','bonus_distance'],(async function*(){for(let i=0;i<stateIndex.totalStates;i++){const m=stateIndex.stateMask[i],u=stateIndex.stateUpper[i];yield[i,m,u,popcount15(m),15-popcount15(m),stateTables.values[i],stateTables.lower[i],stateTables.upper[i],stateTables.upper[i]-stateTables.lower[i],Math.max(0,63-u)];}})());
  const shadowMatrix=Array.from({length:16},()=>Array(13).fill(null)),shadowSum=Array.from({length:16},()=>Array(13).fill(0)),shadowN=Array.from({length:16},()=>Array(13).fill(0));
  await writeLargeCsv(path.join(analysisDir,'bonus_shadow_values.csv'),['used_mask','used_category_count','upper_total','next_upper_total','shadow_value'],(async function*(){for(let i=0;i<stateIndex.totalStates;i++){const m=stateIndex.stateMask[i],u=stateIndex.stateUpper[i];if(u>=63)continue;const j=stateIndex.indexOf(m,u+1);if(j<0)continue;const v=stateTables.values[j]-stateTables.values[i],layer=popcount15(m),d=Math.min(12,Math.floor((63-u)/5));shadowSum[layer][d]+=v;shadowN[layer][d]++;yield[m,layer,u,u+1,v];}})());for(let r=0;r<16;r++)for(let c=0;c<13;c++)shadowMatrix[r][c]=shadowN[r][c]?shadowSum[r][c]/shadowN[r][c]:NaN;
  onProgress({progress:.60,detail:'Exact state and bonus-shadow exports'});

  // Reconstruct a deterministic stratified decision atlas after the exact table is complete.
  // This avoids burdening every one of the 1.43 million DP states with research-only bookkeeping.
  const dice=createDiceUniverse();
  const engine=new PolicyEngine({...stateTables,stateIndex,cacheSize:2048,continuation:'full'});
  const edges=[0,1e-12,1e-8,1e-6,1e-4,1e-3,1e-2,.05,.1,.5,1,2,5,10,Infinity];
  const decisionMetrics={sampleDesign:'32 evenly spaced reachable states per used-category layer (all available where fewer)',sampledStates:0,rolledDecisionPositions:0,decisions:[0,0,0],actionTypes:[[0,0],[0,0],[0,0]],keeperSizes:[Array(5).fill(0),Array(5).fill(0),Array(5).fill(0)],categories:[Array(15).fill(0),Array(15).fill(0),Array(15).fill(0)],marginBins:[Array(edges.length-1).fill(0),Array(edges.length-1).fill(0),Array(edges.length-1).fill(0)],ties:[0,0,0],surprises:[]};
  const expanded=[];
  const addSurprise=x=>{decisionMetrics.surprises.push(x);decisionMetrics.surprises.sort((a,b)=>b.regret-a.regret||a.stateIndex-b.stateIndex);if(decisionMetrics.surprises.length>500)decisionMetrics.surprises.length=500;};
  for(let layer=0;layer<=15;layer++){
    const states=stateIndex.layers[layer];if(!states.length)continue;const count=Math.min(32,states.length);
    for(let q=0;q<count;q++){
      const pos=count===1?0:Math.floor(q*(states.length-1)/(count-1)),idx=states[pos],mask=stateIndex.stateMask[idx],upper=stateIndex.stateUpper[idx];
      if(mask===0x7fff)continue;decisionMetrics.sampledStates++;
      const pol=engine.getPolicy(mask,upper);
      for(let stage=0;stage<3;stage++)for(let rollId=0;rollId<252;rollId++){
        decisionMetrics.decisions[stage]++;decisionMetrics.rolledDecisionPositions++;
        const code=pol.actions[stage][rollId],margin=pol.margins[stage][rollId];let bin=edges.length-2;for(let b=0;b<edges.length-1;b++)if(margin>=edges[b]&&margin<edges[b+1]){bin=b;break;}decisionMetrics.marginBins[stage][bin]++;
        if(margin<=1e-12)decisionMetrics.ties[stage]++;
        if(code&0x8000){const kid=code&0x7fff;decisionMetrics.actionTypes[stage][1]++;decisionMetrics.keeperSizes[stage][dice.keeperSizes[kid]]++;const roll=dice.rolls[rollId],keep=dice.keepers[kid];let maxKeep=0,maxDrop=0;for(let f=0;f<6;f++){if(keep[f])maxKeep=f+1;if(roll[f]>keep[f])maxDrop=f+1;}if(maxDrop>maxKeep&&maxKeep>0&&margin>.25)addSurprise({type:'discard_high_keep_low',stateIndex:idx,rollId,stage,optimalKeeperId:kid,regret:margin,bestValue:null,alternativeValue:null});}
        else {decisionMetrics.actionTypes[stage][0]++;decisionMetrics.categories[stage][code]++;}
        if((margin<.001||margin>2)&&expanded.length<1000){const actions=engine.allActions(mask,upper,rollId,stage).slice(0,20);expanded.push({state_index:idx,used_mask:mask,upper_total:upper,roll_id:rollId,dice:Array.from({length:6},(_,f)=>Array(dice.rolls[rollId][f]).fill(f+1)).flat(),rerolls_remaining:stage,margin,actions});}
      }
    }
  }
  writeJsonAtomic(path.join(analysisDir,'decision_aggregates.json'),decisionMetrics);
  writeJsonAtomic(path.join(analysisDir,'expanded_decision_sample.json'),expanded);
  const surprises=decisionMetrics.surprises.map(x=>({type:x.type,state_index:x.stateIndex,used_mask:stateIndex.stateMask[x.stateIndex],upper_total:stateIndex.stateUpper[x.stateIndex],dice:Array.from({length:6},(_,f)=>Array(dice.rolls[x.rollId][f]).fill(f+1)).flat().join(' '),rerolls_remaining:x.stage,keeper:x.optimalKeeperId!==undefined?Array.from({length:6},(_,f)=>Array(dice.keepers[x.optimalKeeperId][f]).fill(f+1)).flat().join(' '):'',regret:x.regret,best_value:x.bestValue,alternative_value:x.alternativeValue}));
  writeCsv(path.join(csvDir,'surprising_positions.csv'),Object.keys(surprises[0]||{type:'',state_index:'',used_mask:'',upper_total:'',dice:'',rerolls_remaining:'',keeper:'',regret:'',best_value:'',alternative_value:''}),surprises);writeJsonAtomic(path.join(analysisDir,'surprising_positions.json'),surprises);

  const bonusCI=wilsonInterval(pooled.bonusCount,pooled.n),yatzyCI=wilsonInterval(pooled.yatzyGameCount,pooled.n);const master={runId:path.basename(runDir),rulesetId:manifest.rulesetId,rulesHash:manifest.rulesHash,exact:{midpoint:manifest.startingExpectedValue,lower:manifest.startingLowerBound,upper:manifest.startingUpperBound,intervalWidth:manifest.startingUpperBound-manifest.startingLowerBound,stateCount:manifest.stateCount},simulation:{...pooledStats,runs:optimal.length,totalGames:pooled.n,bonusFrequency:pooled.bonusCount/pooled.n,bonusCI95:bonusCI,yatzyFrequency:pooled.yatzyGameCount/pooled.n,yatzyCI95:yatzyCI},thresholds,categories:categoryRows,policies:policyRows,verification:{publicationReady:verification.publicationReady,mandatoryPassed:verification.mandatoryPassed,mandatoryTotal:verification.mandatoryTotal},artifacts:{valuesSha256:manifest.valuesSha256,boundsSha256:manifest.boundsSha256}};writeJsonAtomic(path.join(runDir,'master_results.json'),master);writeCsv(path.join(runDir,'master_results.csv'),['metric','value'],[{metric:'exact_expected_score',value:master.exact.midpoint},{metric:'exact_lower_bound',value:master.exact.lower},{metric:'exact_upper_bound',value:master.exact.upper},{metric:'simulation_mean_10m',value:master.simulation.mean},{metric:'simulation_sd',value:master.simulation.sd},{metric:'bonus_frequency',value:master.simulation.bonusFrequency},{metric:'yatzy_frequency',value:master.simulation.yatzyFrequency}]);

  fs.writeFileSync(path.join(mdDir,'optimal_runs.md'),markdownTable(Object.keys(runRows[0]),runRows));fs.writeFileSync(path.join(texDir,'optimal_runs.tex'),latexTable(Object.keys(runRows[0]),runRows));fs.writeFileSync(path.join(mdDir,'category_summary.md'),markdownTable(Object.keys(categoryRows[0]),categoryRows));fs.writeFileSync(path.join(texDir,'category_summary.tex'),latexTable(Object.keys(categoryRows[0]),categoryRows));fs.writeFileSync(path.join(mdDir,'policy_comparison.md'),markdownTable(Object.keys(policyRows[0]),policyRows));fs.writeFileSync(path.join(texDir,'policy_comparison.tex'),latexTable(Object.keys(policyRows[0]),policyRows));
  onProgress({progress:.72,detail:'Master results and reusable tables'});

  const chart=(fn,args,name)=>{fn({...args,fileBase:path.join(figSvg,name)});const srcPng=path.join(figSvg,`${name}.png`);fs.copyFileSync(srcPng,path.join(figPng,`${name}.png`));fs.unlinkSync(srcPng);};
  chart(barChart,{title:'Reachable states by used-category layer',labels:stateIndex.layers.map((_,i)=>String(i)),values:stateIndex.layers.map(x=>x.length),yLabel:'States'},'01_state_counts_by_layer');
  chart(lineChart,{title:'Simulation convergence to exact expectation',series:[{label:'Cumulative simulation mean',values:optimal.map((x,i)=>optimal.slice(0,i+1).reduce((a,y)=>a+y.aggregate.sum,0)/optimal.slice(0,i+1).reduce((a,y)=>a+y.aggregate.n,0))},{label:'Exact expectation',values:optimal.map(()=>manifest.startingExpectedValue)}],xLabel:'Independent million-game runs',yLabel:'Mean score'},'02_simulation_convergence');
  chart(barChart,{title:'Ten independent optimal-policy means',labels:runRows.map((_,i)=>String(i+1)),values:runRows.map(x=>x.mean),yLabel:'Mean score'},'03_independent_run_means');
  chart(barChart,{title:'Optimal final-score distribution',labels:distribution.filter((_,i)=>i%10===0&&i>=100).map(x=>String(x.score)),values:distribution.filter((_,i)=>i%10===0&&i>=100).map(x=>x.count),yLabel:'Games'},'04_final_score_distribution');
  chart(lineChart,{title:'Empirical cumulative score distribution',series:[{label:'CDF',values:distribution.filter((_,i)=>i>=100&&i%2===0).map(x=>x.cumulative)}],xLabel:'Score index',yLabel:'Cumulative probability'},'05_score_cdf');
  chart(lineChart,{title:'Upper bonus probability by turn',series:[{label:'Bonus earned',values:turnRows.map(x=>x.bonus_probability)}],xLabel:'Turn',yLabel:'Probability'},'06_bonus_probability_by_turn');
  chart(barChart,{title:'Mean score by category',labels:CATEGORY_NAMES.map(x=>x.replaceAll(' ','\n')),values:categoryRows.map(x=>x.mean),yLabel:'Points'},'07_category_means');
  chart(barChart,{title:'Category zero-score frequency',labels:CATEGORY_NAMES,values:categoryRows.map(x=>x.zero_frequency),yLabel:'Frequency'},'08_category_zero_frequency');
  chart(barChart,{title:'Keeper-size distribution under optimal play',labels:keeperRows.map(x=>String(x.keeper_size)),values:keeperRows.map(x=>x.frequency),yLabel:'Frequency'},'09_keeper_sizes');
  chart(barChart,{title:'Mean score by policy',labels:policyRows.map(x=>x.policy),values:policyRows.map(x=>x.mean),yLabel:'Points'},'10_policy_means');
  chart(barChart,{title:'Expected loss relative to optimal',labels:policyRows.map(x=>x.policy),values:policyRows.map(x=>Math.max(0,x.loss_vs_optimal)),yLabel:'Points lost'},'11_policy_loss');
  chart(heatmap,{title:'Marginal value of an additional upper-section point',matrix:shadowMatrix,rowLabels:Array.from({length:16},(_,i)=>String(i)),colLabels:Array.from({length:13},(_,i)=>`${i*5}-${i*5+4}`)},'12_bonus_shadow_heatmap');
  chart(lineChart,{title:'Mean cumulative score by turn',series:[{label:'Cumulative score',values:turnRows.map(x=>x.mean_cumulative_score)},{label:'Upper subtotal',values:turnRows.map(x=>x.mean_upper_subtotal)}],xLabel:'Turn',yLabel:'Points'},'13_turn_trajectories');
  chart(barChart,{title:'Category correlation with final score',labels:CATEGORY_NAMES,values:corrRows.map(x=>Math.abs(x.correlation_with_final_score)),yLabel:'Absolute correlation'},'14_category_correlations');
  chart(barChart,{title:'Decision-margin distribution',labels:marginRows.map(x=>`${x.lower}-${x.upper}`),values:marginRows.map(x=>x.frequency),yLabel:'Frequency'},'15_decision_margins');
  architectureSvg(path.join(figSvg,'16_architecture.svg'),'Scientific pipeline architecture',['Frozen rules and runtime preflight','Exact dynamic-programming precomputation','Independent verification and deterministic rebuild','10 × 1,000,000 optimal simulations','Policy comparisons and exact-state analysis','Figures, tables, evidence dossier, audited bundle']);
  architectureSvg(path.join(figSvg,'17_state_compression.svg'),'State compression',['Complete scorecard and recorded history','Used-category mask M','Capped upper subtotal u','1,430,528 reachable turn-boundary states']);
  architectureSvg(path.join(figSvg,'18_durability_protocol.svg'),'Durable computation protocol',['Compute complete chunk in memory','Write values to canonical offsets','Flush value and bound files','Hash persisted chunk','Commit SQLite completion marker']);
  onProgress({progress:.92,detail:'Figures rendered'});

  const inventory={generatedAt:new Date().toISOString(),tables:fs.readdirSync(csvDir),figuresSvg:fs.readdirSync(figSvg),figuresPng:fs.readdirSync(figPng),analysisFiles:fs.readdirSync(analysisDir)};writeJsonAtomic(path.join(analysisDir,'analysis_inventory.json'),inventory);onProgress({progress:1,detail:'Analysis complete'});return{master,inventory,paths:{analysisDir,tablesDir,figSvg,figPng}};
}
